expname: vangogh

data:
  downscale: 2        # downscale image for training
  reshape_size: 480   # Image Size for calculate style loss

finetune:
  src_text: "a realistic photograph with sharp details, vibrant colors, and natural lighting"
  target_text: "a magical fairytale style with soft pastel colors, warm lighting, and a hand-drawn cel animation feel, inspired by Studio Ghibli"
  w_contrastive: 0.05
  w_patchnce: 0.01
  w_perceptual: 1.1
  w_clip: 0.3
  w_style: 1.0