expname: vangogh

data:
  downscale: 2        # downscale image for training

finetune:
  src_text: "photo"
  target_text: "painting, oil on canvas, Vincent van gogh self-portrait style"
  w_perceptual: 1.1
  w_contrastive: 0.2
  w_patchnce: 0.1
  w_clip: 1.0