expname: vangogh

data:
  downscale: 2        # downscale image for training
  reshape_size: 480   # Image Size for calculate style loss

finetune:
  src_text: "photo"
  target_text: "painting, oil on canvas, Vincent van gogh style artwork"
  w_contrastive: 0.2
  w_patchnce: 0.1
  w_clip: 1.0
  w_style: 0.05