expname: vangogh

finetune:
  src_text: "realistic photograph"
  target_text: "soft pastel colors, warm lighting, hand-drawn cel animation, inspired by Studio Ghibli"
  w_contrastive: 0.1
  w_perceptual: 0.1
  w_clip: 0.4
  w_style: 1.0